version: '3.9'
services:
  demo:
    image: "docker.io/persesdev/perses:v0.28.0"
    ports:
      - "5000:8080"
    labels:
      - "traefik.enable=true"
      # The domain the service will respond to
      - "traefik.http.routers.demo.rule=Host(`demo.perses.dev`)"
      - "traefik.http.routers.demo.tls.certresolver=myresolver"
  traefik:
    image: "docker.io/traefik:v2.9.10"
    command:
      - "--providers.docker=true"
      # https://doc.traefik.io/traefik/user-guides/docker-compose/acme-tls/
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=perses-team@googlegroups.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
    volumes:
      # So that Traefik can listen to the Docker events
      - "/run/user/1000/podman/podman.sock:/var/run/docker.sock"
      - "./letsencrypt:/letsencrypt"
