site_name: Perses
site_url: "https://perses.dev"
repo_name: "Perses on GitHub"
repo_url: "https://github.com/perses/perses"
theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: black
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: black
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.tabs
    - content.code.copy
markdown_extensions: 
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: "#"
  - admonition
extra_css:
  - 'css/style.css'
# extra_javascript:
#   - 'js/main.js'

# Enable versioning
extra:
  version:
    provider: mike

nav:
  - 'Home': 'index.md'
  - 'Docs':
      - 'docs/index.md'
      - 'User Guides':
          - 'Configuration': 'docs/user-guides/configuration.md'
          - 'Dashboard as Code': 'docs/user-guides/dashboardascode.md'
          - 'Embedding Perses Panels': 'docs/user-guides/embeddingpanels.md'
          - 'Installing from the Source': 'docs/user-guides/installingfromsource.md'
          - 'Installing in a Container': 'docs/user-guides/installingincontainer.md'
          - 'OAuth Configuration': 'docs/user-guides/oauthconfiguration.md'
          - 'Provisioning': 'docs/user-guides/provisioning.md'
      - 'Design Docs':
          - 'Authentication': 'docs/design/authentication.md'
          - 'Authorization': 'docs/design/authorization.md'
          - 'Perses on Kubernetes': 'docs/design/kubernetes.md'
      - 'API':
          - 'API Reference': 'docs/api/index.md'
          - 'Dashboard': 'docs/api/dashboard.md'
          - 'Datasource': 'docs/api/datasource.md'
          - 'Ephemeral Dashboard': 'docs/api/ephemeral-dashboard.md'
          - 'Project': 'docs/api/project.md'
          - 'Role': 'docs/api/role.md'
          - 'Role Binding': 'docs/api/rolebinding.md'
          - 'Secret': 'docs/api/secret.md'
          - 'User': 'docs/api/user.md'
          - 'Variable': 'docs/api/variable.md'
      - 'Dashboard as Code':
        - 'Cue':
            - 'Cue Reference': 'docs/dac/cue/index.md'
            - 'Dashboard Builder': 'docs/dac/cue/dashboardbuilder.md'
            - 'Filter Builder': 'docs/dac/cue/filterbuilder.md'
            - 'Label Names Variable Builder': 'docs/dac/cue/labelnamesvariablebuilder.md'
            - 'Label Values Variable Builder': 'docs/dac/cue/labelvaluesvariablebuilder.md'
            - 'Panel Groups Builder': 'docs/dac/cue/panelgroupsbuilder.md'
            - 'Prometheus Panel Builder': 'docs/dac/cue/prometheuspanelbuilder.md'
            - 'PromQL Variable Builder': 'docs/dac/cue/promqlvariablebuilder.md'
            - 'Static List Variable Builder': 'docs/dac/cue/staticlistvariablebuilder.md'
            - 'Text Variable Builder': 'docs/dac/cue/textvariablebuilder.md'
            - 'Variable Group Builder': 'docs/dac/cue/variablegroupbuilder.md'
        - 'Go':
            - 'Go Reference': 'docs/dac/go/index.md'
            - 'Dashboard Builder': 'docs/dac/go/dashboardbuilder.md'
            - 'Datasource Builder': 'docs/dac/go/datasourcebuilder.md'
            - 'Panel Builder': 'docs/dac/go/panelbuilder.md'
            - 'Panel Group Builder': 'docs/dac/go/panelgroupbuilder.md'
            - 'Query Builder': 'docs/dac/go/querybuilder.md'
           - 'Variable Builder': 'docs/dac/go/variablebuilder.md'
            - 'Variable Group Builder': 'docs/dac/go/variablegroupbuilder.md'
            - 'Bar Panel Builder': 'docs/dac/go/barpanelbuilder.md'
            - 'Guage Panel Builder': 'docs/dac/go/guagepanelbuilder.md'
            - 'Markdown Panel Builder': 'docs/dac/go/markdownpanelbuilder.md'
            - 'Stat Panel Builder': 'docs/dac/go/statpanelbuilder.md'
            - 'Time Series Panel Builder': 'docs/dac/go/timeseriespanelbuilder.md'
            - 'HTTP Builder': 'docs/dac/go/httpbuilder.md'
            - 'Prometheus Datasource Builder': 'docs/dac/go/prometheusdatasourcebuilder.md'
            - 'Prometheus Query Builder': 'docs/dac/go/prometheusquerybuilder.md'
            - 'PromQL Variable Builder': 'docs/dac/go/promqlvariablebuilder.md'
            - 'Label Names Variable Builder': 'docs/dac/go/labelnamesvariablebuilder.md'
            - 'Label Values Variable Builder': 'docs/dac/go/labelvaluesvariablebuilder.md'
      - 'Plugins':
          - 'Plugins Reference': 'docs/plugins/index.md'
          - 'CUE in Perses': 'docs/plugins/cue.md'
          - 'Panel Plugins': 'docs/plugins/panelplugins.md'
          - 'Prometheus Plugins': 'docs/plugins/prometheusplugins.md'
      - 'Tooling':
          - 'Tooling Reference': 'docs/tooling/index.md'
          - 'Perses CLI (percli)': 'docs/tooling/percli.md'
  - 'Demo': 'https://demo.perses.dev'

copyright: The Linux Foundation has registered trademarks and uses trademarks. For a list of trademarks of The Linux Foundation, please see our <a href="https://www.linuxfoundation.org/legal/trademark-usage" target="_blank">Trademark Usage page</a>.
